# Generated by Django 3.2.4 on 2022-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('D/HCW/MS', 'Doctor/Health Care Worker/Medical Staff'), ('I/SP', 'Insurance/Health Service Provider'), ('MSh', 'Medical Shop')], default=None, max_length=20, verbose_name='Do any of the following apply to you'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_no',
            field=models.CharField(default=None, max_length=20, verbose_name='Registration No./License ID'),
        ),
    ]
