# Generated by Django 3.2.4 on 2022-03-20 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medworkerrep',
            name='contact_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact Number'),
        ),
    ]
