# Generated by Django 3.2.4 on 2022-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0002_auto_20220209_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
