# Generated by Django 3.2.4 on 2022-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0007_alter_medworkerrep_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('D/HCW/MS', 'Doctor/Health Care Worker/Medical Staff'), ('I/SP', 'Insurance/Health Service Provider'), ('MSh', 'Medical Shop'), ('NoU', 'Normal User')], default='NoU', max_length=20, null=True, verbose_name='Division'),
        ),
    ]
