# Generated by Django 3.2.4 on 2022-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0009_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='medworkerrep',
            name='full_com_name',
            field=models.CharField(default=None, max_length=200, verbose_name='Full Name/Company Name'),
        ),
        migrations.AddField(
            model_name='patients',
            name='full_name',
            field=models.CharField(default=None, max_length=200, verbose_name='Full Name'),
        ),
    ]
