# Generated by Django 3.2.4 on 2022-02-10 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0010_auto_20220210_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medworkerrep',
            options={'verbose_name_plural': 'Medical Workers/Insurance Representives/Pharmaceutical Shops'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='medworkerrep',
            name='hcwvid',
            field=models.CharField(default=None, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Health Care Worker/Vendor ID'),
        ),
    ]
