# Generated by Django 3.2.4 on 2022-02-10 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0011_auto_20220210_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medworkerrep',
            name='hcwvid',
            field=models.CharField(default=None, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Health Care Worker/Vendor ID'),
        ),
    ]
