# Generated by Django 3.2.4 on 2022-02-12 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medworkerrep',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='mwr_notifs', to='health_tracker.Notification'),
        ),
        migrations.AddField(
            model_name='patients',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='p_notifs', to='health_tracker.Notification'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='wbid',
            field=models.CharField(default=None, max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Well-Being ID'),
        ),
    ]
