# Generated by Django 3.2.4 on 2022-02-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0015_auto_20220212_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tags/Keywords')),
                ('file', models.FileField(default=None, unique=True, upload_to='', verbose_name='File Path')),
                ('recipent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recipent', to='health_tracker.patients', verbose_name='Recipent')),
                ('uploader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='health_tracker.medworkerrep', verbose_name='Uploaded By')),
            ],
        ),
    ]
