# Generated by Django 3.2.4 on 2022-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0016_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='vendor_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Name of person uploading this documen'),
        ),
    ]
