# Generated by Django 3.2.4 on 2022-02-25 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0017_files_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 15, 18, 31, 859248)),
        ),
    ]
