# Generated by Django 3.2.5 on 2022-02-25 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0018_files_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medworkerrep',
            name='date_of_approval',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 9, 51, 11, 4668)),
        ),
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 9, 51, 11, 8273)),
        ),
    ]
