# Generated by Django 3.2.5 on 2022-02-25 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0019_auto_20220225_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medworkerrep',
            name='date_of_approval',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
