# Generated by Django 3.2.4 on 2022-02-25 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0020_auto_20220225_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medworkerrep',
            name='date_of_approval',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_of_approval',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='files',
            name='vendor_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Name of person uploading this document'),
        ),
    ]
