# Generated by Django 3.2.4 on 2022-02-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0023_healthvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by', to='health_tracker.medworkerrep', verbose_name='Last Updated By'),
        ),
        migrations.AlterField(
            model_name='healthvalue',
            name='patient_value',
            field=models.IntegerField(default=None, verbose_name="Patient's Value"),
        ),
    ]
