# Generated by Django 3.2.4 on 2022-02-27 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0024_auto_20220227_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
