# Generated by Django 3.2.4 on 2022-03-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0025_healthstatus_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(choices=[('PRSCN', 'Presctiption'), ('S/T', 'Schedule/Timetable'), ('HR/TR', 'Health Report/Test Report'), ('INVCE', 'Invoice'), ('OP', 'Operative Report'), ('DS', 'Discharge Summary'), ('MSC', 'Miscellaneous')], default='MSC', max_length=20, verbose_name='File Type'),
        ),
    ]
