# Generated by Django 3.2.4 on 2022-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0027_alter_files_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthvalue',
            name='condition_category',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('BDL-SAFE', 'Borderline-Safe'), ('BDL-DANGER', 'Borderline-Danger'), ('NA', 'Not Applicable')], default='NA', max_length=20, verbose_name='Health Condition Category'),
        ),
    ]
