# Generated by Django 3.2.4 on 2022-03-14 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0030_auto_20220314_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medworkerrep',
            name='address',
            field=models.CharField(default=None, max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='medworkerrep',
            name='city',
            field=models.CharField(default=None, max_length=30, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='medworkerrep',
            name='pincode',
            field=models.CharField(default=None, max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
