# Generated by Django 3.2.4 on 2022-03-14 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0031_auto_20220314_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medworkerrep',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='medworkerrep',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='medworkerrep',
            name='pincode',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
