# Generated by Django 3.2.4 on 2022-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0033_medworkerrep_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medworkerrep',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='City/Town'),
        ),
    ]
