# Generated by Django 3.2.4 on 2022-03-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0034_alter_medworkerrep_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthvalue',
            name='condition_category',
            field=models.CharField(choices=[('', ''), ('SAFE', 'Safe'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('BDL-SAFE', 'Borderline-Safe'), ('BDL-DANGER', 'Borderline-Danger'), ('NA', 'Not Applicable')], default=None, max_length=20, verbose_name='Health Condition Category'),
        ),
    ]
